[project]
name = "kspo-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.7"
dependencies = [
    "ipykernel>=6.29.5",
    "ipython>=8.30.0",
    "pandas>=2.2.3",
    "pyarrow>=18.1.0",
]
